# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException

class TestReview():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.wait = WebDriverWait(self.driver, 10)  # Add explicit wait with 10 seconds timeout
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_review(self):
    try:
      # Navigate to the website
      self.driver.get("http://localhost/project/")
      self.driver.set_window_size(1552, 832)
      
      # Click login button and wait for login form
      login_btn = self.wait.until(EC.element_to_be_clickable((By.ID, "loginSignupBtn")))
      login_btn.click()
      
      # Fill in login credentials
      email_field = self.wait.until(EC.presence_of_element_located((By.ID, "login-email")))
      email_field.send_keys("tomshibugenai2024@gmail.com")
      
      password_field = self.wait.until(EC.presence_of_element_located((By.ID, "login-password")))
      password_field.send_keys("Appu2020@")
      
      # Click submit and wait for page to load
      submit_btn = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".submit-button:nth-child(4)")))
      submit_btn.click()
      
      # Wait for page to load after login
      time.sleep(2)  # Give some time for the page to fully load
      
      # Navigate to reviews page
      reviews_link = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "a[href='reviews.php']")))
      reviews_link.click()
      
      # Wait for reviews page to load
      time.sleep(2)
      
      # Check if there are any bookings to review
      try:
        # First check if there's a "No Bookings Found" message
        no_bookings = self.driver.find_element(By.CLASS_NAME, "no-bookings")
        if no_bookings.is_displayed():
          print("No bookings found. Please make a booking first.")
          return
      except NoSuchElementException:
        # If no "no-bookings" element is found, proceed with review
        pass
      
      # Try to find the review button with different possible selectors
      review_button_selectors = [
        ".station-card:nth-child(1) .btn-primary",
        ".station-card:nth-child(1) .btn",
        ".station-card:nth-child(1) button",
        "button[name='submit_review']"
      ]
      
      review_btn = None
      for selector in review_button_selectors:
        try:
          review_btn = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, selector)))
          if review_btn.is_displayed():
            break
        except TimeoutException:
          continue
      
      if not review_btn:
        raise TimeoutException("Could not find review button. Please check if you have any bookings.")
      
      review_btn.click()
      
      # Wait for review form to appear and fill in the review
      try:
        # Try different selectors for the rating stars
        rating_selectors = [
          ".star-rating label:nth-child(4)",
          ".star-rating input[value='4'] + label",
          ".star-rating .fas.fa-star:nth-child(4)"
        ]
        
        rating_star = None
        for selector in rating_selectors:
          try:
            rating_star = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, selector)))
            if rating_star.is_displayed():
              break
          except TimeoutException:
            continue
        
        if rating_star:
          rating_star.click()
        else:
          raise TimeoutException("Could not find rating stars")
        
        # Try to find the review text area
        review_text = self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "textarea[name='review_text']")))
        review_text.send_keys("good")
        
        # Submit the review
        submit_review = self.wait.until(EC.element_to_be_clickable((By.NAME, "submit_review")))
        submit_review.click()
        
        # Wait for success message
        success_message = self.wait.until(EC.presence_of_element_located((By.CLASS_NAME, "alert-success")))
        assert "success" in success_message.text.lower()
        
      except TimeoutException as e:
        print(f"Error during review submission: {str(e)}")
        raise
      
    except Exception as e:
      print(f"Test failed: {str(e)}")
      # Take a screenshot of the current page for debugging
      self.driver.save_screenshot("test_failure.png")
      raise
  
