# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://localhost/project/index.php")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-container").click()
    self.driver.find_element(By.ID, "loginSignupBtn").click()
    self.driver.find_element(By.ID, "login-email").click()
    self.driver.find_element(By.ID, "login-email").send_keys("tomshibu49@gmail.com")
    self.driver.find_element(By.ID, "login-password").send_keys("Tomshibu20@")
    self.driver.find_element(By.ID, "login-password").send_keys(Keys.ENTER)
  
