# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException, ElementClickInterceptedException
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEnquiry():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.wait = WebDriverWait(self.driver, 10)  # Add explicit wait
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_element(self, by, value, timeout=10):
    """Helper method to wait for an element to be present and visible"""
    try:
        element = WebDriverWait(self.driver, timeout).until(
            EC.presence_of_element_located((by, value))
        )
        return element
    except TimeoutException:
        print(f"Timeout waiting for element: {value}")
        raise

  def wait_for_element_clickable(self, by, value, timeout=10):
    """Helper method to wait for an element to be clickable"""
    try:
        element = WebDriverWait(self.driver, timeout).until(
            EC.element_to_be_clickable((by, value))
        )
        return element
    except TimeoutException:
        print(f"Timeout waiting for element to be clickable: {value}")
        raise

  def login(self, email, password):
    """Helper method to handle login process"""
    try:
        print("Starting login process...")
        
        # Click login button and wait for login form
        print("Looking for login button...")
        login_btn = self.wait_for_element_clickable(By.ID, "loginSignupBtn")
        print("Found login button, clicking...")
        login_btn.click()
        
        # Wait for login modal to be visible and fully loaded
        print("Waiting for login modal...")
        login_modal = self.wait_for_element(By.ID, "loginModal")
        self.wait.until(EC.visibility_of(login_modal))
        time.sleep(2)  # Give extra time for modal to be fully rendered
        
        # Fill in login credentials
        print("Filling in email...")
        email_field = self.wait_for_element_clickable(By.ID, "login-email")
        email_field.clear()  # Clear any existing text
        email_field.send_keys(email)
        
        print("Filling in password...")
        password_field = self.wait_for_element_clickable(By.ID, "login-password")
        password_field.clear()  # Clear any existing text
        password_field.send_keys(password)
        
        # Wait for submit button to be clickable and click it
        print("Looking for submit button...")
        submit_btn = self.wait_for_element_clickable(By.CSS_SELECTOR, ".submit-button")
        
        # Try multiple methods to click the button
        print("Attempting to click submit button...")
        try:
            # First try regular click
            submit_btn.click()
        except ElementClickInterceptedException:
            print("Regular click failed, trying JavaScript click...")
            # If that fails, try JavaScript click
            self.driver.execute_script("arguments[0].click();", submit_btn)
        
        print("Waiting for login modal to close...")
        # Wait for login modal to close
        self.wait.until(EC.invisibility_of_element_located((By.ID, "loginModal")))
        
        # Wait for page to load after login
        print("Waiting for page to load after login...")
        time.sleep(3)  # Increased wait time
        
        # Verify login success by checking for user-specific elements
        print("Verifying login success...")
        try:
            # Try multiple selectors for user profile
            user_selectors = [
                (By.CSS_SELECTOR, ".user-profile"),
                (By.CSS_SELECTOR, ".logged-in-user"),
                (By.CSS_SELECTOR, ".user-menu"),
                (By.CSS_SELECTOR, ".profile-dropdown"),
                (By.CSS_SELECTOR, "[data-test='user-profile']")
            ]
            
            for selector in user_selectors:
                try:
                    self.wait.until(EC.presence_of_element_located(selector))
                    print(f"Login successful - found user element with selector: {selector}")
                    return True
                except TimeoutException:
                    continue
            
            print("Login verification failed - no user profile elements found")
            # Take a screenshot for debugging
            self.driver.save_screenshot("login_failure.png")
            return False
            
        except Exception as e:
            print(f"Error during login verification: {str(e)}")
            self.driver.save_screenshot("login_verification_error.png")
            return False
        
    except Exception as e:
        print(f"Login process failed: {str(e)}")
        # Take a screenshot for debugging
        self.driver.save_screenshot("login_process_failure.png")
        return False

  def test_enquiry(self):
    try:
      print("Starting test...")
      # Navigate to the website
      self.driver.get("http://localhost/project/index.php")
      self.driver.set_window_size(1552, 832)
      
      # Click nav container and wait for it to be clickable
      print("Looking for nav container...")
      nav_container = self.wait_for_element_clickable(By.CSS_SELECTOR, ".nav-container")
      nav_container.click()
      
      # Attempt login
      print("Attempting login...")
      if not self.login("tomshibugenai2024@gmail.com", "Appu2020@"):
        raise Exception("Login failed")
      
      # Wait for page to load after login
      time.sleep(2)
      
      # Wait for and click the station select dropdown
      print("Looking for station select dropdown...")
      station_select = self.wait_for_element_clickable(By.ID, "stationSelect")
      station_select.click()
      
      # Wait for and select the option
      print("Selecting station option...")
      option = self.wait_for_element_clickable(By.XPATH, "//option[. = 'FGH']")
      option.click()
      
      # Wait for and fill in the enquiry subject
      print("Filling in enquiry subject...")
      subject_field = self.wait_for_element_clickable(By.ID, "enquirySubject")
      subject_field.clear()
      subject_field.send_keys("abc")
      
      # Wait for and fill in the enquiry message
      print("Filling in enquiry message...")
      message_field = self.wait_for_element_clickable(By.ID, "enquiryMessage")
      message_field.clear()
      message_field.send_keys("abc")
      
      # Wait for and click the submit button
      print("Looking for submit button...")
      submit_btn = self.wait_for_element_clickable(By.CSS_SELECTOR, ".submit-button:nth-child(1)")
      submit_btn.click()
      
      # Wait for success message or confirmation
      print("Waiting for success message...")
      try:
        success_message = self.wait.until(
          EC.presence_of_element_located((By.CSS_SELECTOR, ".alert-success, .success-message"))
        )
        print("Enquiry submitted successfully")
      except TimeoutException:
        print("No success message found after submission")
      
    except Exception as e:
      print(f"Test failed: {str(e)}")
      # Take a screenshot of the current page for debugging
      self.driver.save_screenshot("test_failure.png")
      raise
  
