# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGeolocation():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_geolocation(self):
    self.driver.get("http://localhost/project/cs/geolocation.php")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".locate-btn").click()
    self.driver.find_element(By.ID, "searchRadius").click()
    dropdown = self.driver.find_element(By.ID, "searchRadius")
    dropdown.find_element(By.XPATH, "//option[. = '20 km']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".locate-btn").click()
  
