# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import StaleElementReferenceException

class TestEnq():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.wait = WebDriverWait(self.driver, 10)  # Add explicit wait with 10 second timeout
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_enq(self):
    # Navigate to the page
    self.driver.get("http://localhost/project/index.php")
    self.driver.set_window_size(1552, 832)
    
    # Login process
    login_btn = self.wait.until(EC.element_to_be_clickable((By.ID, "loginSignupBtn")))
    login_btn.click()
    
    email_field = self.wait.until(EC.presence_of_element_located((By.ID, "login-email")))
    email_field.click()
    email_field.send_keys("tomshibugenai2024@gmail.com")
    
    password_field = self.wait.until(EC.presence_of_element_located((By.ID, "login-password")))
    password_field.click()
    password_field.send_keys("Appu2020@")
    
    submit_button = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".submit-button:nth-child(4)")))
    submit_button.click()
    
    # Wait for the page to reload and stabilize after login
    time.sleep(2)  # Give the page a moment to start reloading
    
    # Wait for station select with retry logic
    max_retries = 3
    for attempt in range(max_retries):
        try:
            # Wait for the select element to be both present and clickable
            station_select = self.wait.until(
                EC.presence_of_element_located((By.ID, "stationSelect"))
            )
            self.wait.until(
                EC.element_to_be_clickable((By.ID, "stationSelect"))
            )
            station_select.click()
            
            # Wait for and select the option
            option = self.wait.until(EC.presence_of_element_located((By.XPATH, "//option[. = 'FGH']")))
            option.click()
            break
        except StaleElementReferenceException:
            if attempt == max_retries - 1:  # Last attempt
                raise  # Re-raise the exception if all retries failed
            time.sleep(1)  # Wait before retrying
    
    # Fill in enquiry details
    subject_field = self.wait.until(EC.presence_of_element_located((By.ID, "enquirySubject")))
    subject_field.click()
    subject_field.send_keys("hello")
    
    message_field = self.wait.until(EC.presence_of_element_located((By.ID, "enquiryMessage")))
    message_field.send_keys("hii")
    
    # Submit the enquiry
    submit_enquiry = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".submit-button:nth-child(1)")))
    submit_enquiry.click()
  
